//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneProjeEntities : DbContext
    {
        public HastaneProjeEntities()
            : base("name=HastaneProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Branslar> Tbl_Branslar { get; set; }
        public virtual DbSet<Tbl_Doktorlar> Tbl_Doktorlar { get; set; }
        public virtual DbSet<Tbl_Hastalar> Tbl_Hastalar { get; set; }
        public virtual DbSet<Tbl_ilaclar> Tbl_ilaclar { get; set; }
        public virtual DbSet<Tbl_Kayitlar> Tbl_Kayitlar { get; set; }
        public virtual DbSet<Tbl_Randevular> Tbl_Randevular { get; set; }
        public virtual DbSet<Tbl_Sekreter> Tbl_Sekreter { get; set; }
        public virtual DbSet<vDoktorlar> vDoktorlar { get; set; }
        public virtual DbSet<vRandevu> vRandevu { get; set; }
        public virtual DbSet<vIlaclar> vIlaclar { get; set; }
    }
}
