//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Randevular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Randevular()
        {
            this.Tbl_Kayitlar = new HashSet<Tbl_Kayitlar>();
        }
    
        public int Randevuid { get; set; }
        public string RandevuTarih { get; set; }
        public string RandevuSaat { get; set; }
        public Nullable<int> Doktorid { get; set; }
        public Nullable<bool> RandevuDurum { get; set; }
        public Nullable<int> Sekreterid { get; set; }
        public Nullable<int> Hastaid { get; set; }
        public string HastaSikayet { get; set; }
        public string HastaTeshis { get; set; }
    
        public virtual Tbl_Doktorlar Tbl_Doktorlar { get; set; }
        public virtual Tbl_Hastalar Tbl_Hastalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kayitlar> Tbl_Kayitlar { get; set; }
        public virtual Tbl_Sekreter Tbl_Sekreter { get; set; }
    }
}
