//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sekreter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sekreter()
        {
            this.Tbl_Randevular = new HashSet<Tbl_Randevular>();
        }
    
        public int Sekreterid { get; set; }
        public string SekreterAdSoyad { get; set; }
        public string SekreterTc { get; set; }
        public string SekreterSifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Randevular> Tbl_Randevular { get; set; }
    }
}
