//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Doktorlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Doktorlar()
        {
            this.Tbl_Randevular = new HashSet<Tbl_Randevular>();
        }
    
        public int Doktorid { get; set; }
        public string DoktorAdSoyad { get; set; }
        public Nullable<int> Bransid { get; set; }
        public string DoktorTc { get; set; }
        public string DoktorSifre { get; set; }
        public Nullable<int> MuaneSayisi { get; set; }
        public Nullable<bool> DoktorDurum { get; set; }
    
        public virtual Tbl_Branslar Tbl_Branslar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Randevular> Tbl_Randevular { get; set; }
    }
}
