//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kayitlar
    {
        public int kayitid { get; set; }
        public Nullable<int> Randevuid { get; set; }
        public Nullable<int> ilacid { get; set; }
    
        public virtual Tbl_ilaclar Tbl_ilaclar { get; set; }
        public virtual Tbl_Randevular Tbl_Randevular { get; set; }
    }
}
