//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hastalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Hastalar()
        {
            this.Tbl_Randevular = new HashSet<Tbl_Randevular>();
        }
    
        public int Hastaid { get; set; }
        public string HastaAdSoyad { get; set; }
        public string HastaTc { get; set; }
        public string HastaTelefon { get; set; }
        public string HastaSifre { get; set; }
        public Nullable<byte> HastaCinsiyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Randevular> Tbl_Randevular { get; set; }
    }
}
