//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilk
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDoktorlar
    {
        public string DoktorAdSoyad { get; set; }
        public string DoktorTc { get; set; }
        public string DoktorSifre { get; set; }
        public string BransAd { get; set; }
        public int Doktorid { get; set; }
        public Nullable<int> MuaneSayisi { get; set; }
        public Nullable<bool> DoktorDurum { get; set; }
    }
}
