//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilk
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRandevu
    {
        public string DoktorAdSoyad { get; set; }
        public string HastaAdSoyad { get; set; }
        public int Randevuid { get; set; }
        public string RandevuTarih { get; set; }
        public string RandevuSaat { get; set; }
        public Nullable<bool> RandevuDurum { get; set; }
        public string BransAd { get; set; }
        public int Doktorid { get; set; }
        public int Hastaid { get; set; }
        public Nullable<bool> DoktorDurum { get; set; }
        public string HastaSikayet { get; set; }
        public string HastaTeshis { get; set; }
    }
}
